train_file: ''
test_file: ''
val_file: ''

coco_root: ''
flickr30k_root: ''

bert_config: 'configs/config_bert.json'

image_res: 336
batch_size_train: 256
vision_width: 1024
distill: True
clip_name: "ViT-L-14"
batch_size_test: 64 
k_test: 128

alpha: 0.4
warm_up: True

eos: '[SEP]'

optimizer: {opt: adamW, lr1: 3e-5, lr2: 5e-6, weight_decay: 0.02}
schedular: {sched: cosine, lr: 3e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
use_checkpoint: true
